/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-04-06 07:30:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.movie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class finance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write(" \t.red {color:red; font-weight:bold;}\r\n");
      out.write(" \t.blue {color: blue; font-weight: bold;}\r\n");
      out.write(" </style>   \r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<table id=\"tblFinance\"></table>\r\n");
      out.write("\t<script id=\"tempFinance\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=400>{{title}}</td>\r\n");
      out.write("\t\t\t<td width=100 class=\"{{color}}\">{{price}}</td>\r\n");
      out.write("\t\t\t<td width=100 class=\"{{color}}\">{{range}}</td>\r\n");
      out.write("\t\t\t<td width=100 class=\"{{color}}\">{{percent}}</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tgetFinance();\r\n");
      out.write("\tfunction getFinance(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"/crawl/finance.json\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t//배열에 데이터저장\r\n");
      out.write("\t\t\t\tvar finance = [];\r\n");
      out.write("\t\t\t\tvar i=0;\r\n");
      out.write("\t\t\t\t$(data).each(function(){\r\n");
      out.write("\t\t\t\t\tfinance[i]=this;\r\n");
      out.write("\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//출력\r\n");
      out.write("\t\t\t\tvar i=0;\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#tempFinance\").html());\r\n");
      out.write("\t\t\t\tvar interval = setInterval(function(){\r\n");
      out.write("\t\t\t\t\t$(\"#tblFinance\").html(temp(finance[i % finance.length]));\r\n");
      out.write("\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t\t},2000);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
