/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-04-07 22:52:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.movie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#movies {width:900px; overflow:hidden; margin:0px auto;}\r\n");
      out.write("\t.movie {width: 200px; float:left; margin:10px;}\r\n");
      out.write("\t.name, .odate, .cdate{width:150px; font-size:12px; font-weight:bold; padding:5px;}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<div id=\"movies\"></div>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each list}}\r\n");
      out.write("\t\t<div class=\"movie\">\r\n");
      out.write("\t\t\t<div><img src=\"/display?fileName={{image}}\" width=150></div>\r\n");
      out.write("\t\t\t<div><p class=\"ellipsis name\">{{title}}</p></div>\r\n");
      out.write("\t\t\t<div><p class=\"ellipsis odate\">{{display odate}}</p></div>\r\n");
      out.write("\t\t\t<div><p class=\"ellipsis cdate\">{{display cdate}}</p></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"pagination\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tHandlebars.registerHelper(\"display\", function(odate){\r\n");
      out.write("\t\t\treturn odate.substr(0,11);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar page=1;\r\n");
      out.write("\tgetList();\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"/movie/list.json\",\r\n");
      out.write("\t\t\tdata: {page:page},\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tvar template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#movies\").html(template(data));\r\n");
      out.write("\t\t\t\t$(\".pagination\").html(getPagination(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".pagination\").on(\"click\", \"a\", function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tpage=$(this).attr(\"href\");\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
