/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2022-04-10 23:43:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("   <title>채팅방</title>\n");
      out.write("   <link rel=\"stylesheet\" href=\"/resources/chat.css\"/>\n");
      out.write("   <script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.1.5/sockjs.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".sender.right{\n");
      out.write("\tdisplay:none;\n");
      out.write("}\n");
      out.write(".message.left{\n");
      out.write("\tdisplay:none;\n");
      out.write("}\n");
      out.write(".delete.left{\n");
      out.write("\tdisplay:none;\n");
      out.write("}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("   <div class=\"chat_wrap\">\n");
      out.write("      <div class=\"header\">채팅방(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</div>\n");
      out.write("      <div id=\"chat\"></div>\n");
      out.write("    <script id=\"temp\" type=\"text/x-handlebars-template\">\n");
      out.write("\t\t{{#each .}}\n");
      out.write("\t\t\t<div class=\"{{display sender}}\">\n");
      out.write("\t\t\t\t<div class=\"sender {{display sender}}\">\n");
      out.write("\t\t\t\t\t<img src=\"/display?fileName={{image}}\" style=\"width:50px;border-radius:50%\">\n");
      out.write("\t\t\t\t\t{{sender}}\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"message\">\n");
      out.write("\t\t\t\t{{message}}\n");
      out.write("\t\t\t\t<a href=\"{{id}}\" class=\"delete {{display sender}}\">x</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"date\">{{regdate}}</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t{{/each}}\n");
      out.write("\t\t</script>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      <script>\n");
      out.write("         Handlebars.registerHelper(\"display\", function(sender){\n");
      out.write("            if(sender==\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\n");
      out.write("               return \"right\";\n");
      out.write("            }else{\n");
      out.write("               return \"left\";\n");
      out.write("            }\n");
      out.write("         });\n");
      out.write("      \n");
      out.write("     \n");
      out.write("      </script>\n");
      out.write("      <div class=\"input-div\">\n");
      out.write("         <textarea id=\"txtMessage\" placeholder=\"내용을입력하세요.\"></textarea>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("   var uid=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\tgetChat();\n");
      out.write("\t\n");
      out.write("\t//목록 출력(chat )\n");
      out.write("   function getChat(){\n");
      out.write("\t   $.ajax({\n");
      out.write("\t\t \ttype:\"get\",\n");
      out.write("\t\t \turl:\"/chat/list.json\",\n");
      out.write("\t\t \tdataType:\"json\",\n");
      out.write("\t\t \tsuccess:function(data){\n");
      out.write("\t\t \t\tvar template = Handlebars.compile($(\"#temp\").html());\n");
      out.write("\t\t \t\t$(\"#chat\").html(template(data));\n");
      out.write("\t\t \t\twindow.scrollTo(0,$(\"#chat\").prop(\"scrollHeight\"));\n");
      out.write("\t\t \t}\n");
      out.write("\t   });  \n");
      out.write("   }\n");
      out.write("   //메시지 삭제\n");
      out.write("   $(\"#chat\").on(\"click\",\".message a\",function(e){\n");
      out.write("\t   e.preventDefault();\n");
      out.write("\t var id=$(this).attr(\"href\");\n");
      out.write("\t if(!confirm(\"메시지를 살제하실래요?\")) return;\n");
      out.write("\t \t$.ajax({\n");
      out.write("\t \t\ttype:\"post\",\n");
      out.write("\t \t\turl:\"/chat/delete\",\n");
      out.write("\t \t\tdata:{id:id},\n");
      out.write("\t \t\tsuccess:function(){\n");
      out.write("\t \t\tgetChat();\n");
      out.write("\t \t\tsock.send(\"delete\");\n");
      out.write("\t \t\t\t\n");
      out.write("\t \t\t}\n");
      out.write("\t \t})\n");
      out.write("\t   \n");
      out.write("   });\n");
      out.write("   \n");
      out.write("   //Enter key\n");
      out.write("   $(\"#txtMessage\").on(\"keydown\",function(e){\n");
      out.write("      if(e.keyCode==13 && !e.shiftKey){\n");
      out.write("         e.preventDefault();\n");
      out.write("         var message = $(this).val();\n");
      out.write("         if(message==\"\"){\n");
      out.write("            alert(\"보내실 내용을 입력하세요!\")\n");
      out.write("            return;\n");
      out.write("         }\n");
      out.write("         //체팅데이터 입력\n");
      out.write("         $.ajax({\n");
      out.write("        \ttype:\"post\",\n");
      out.write("\t\t\turl:\"/chat/insert\",\n");
      out.write("\t\t\tdata:{sender:uid,message:message},\n");
      out.write("\t\t\tsuccess:function(){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("         });\n");
      out.write("         sock.send(uid + \"|\" + message);\n");
      out.write("         $(\"#txtMessage\").val(\"\");\n");
      out.write("      }\n");
      out.write("   });\n");
      out.write("\n");
      out.write("   //소켓설정\n");
      out.write("   var sock = new SockJS(\"http://localhost:8080/sock_chat\");\n");
      out.write("   sock.onmessage = onMessage;\n");
      out.write("  \n");
      out.write("   //서버에서 메시지를 받을때\n");
      out.write("   function onMessage(msg){\n");
      out.write("    \tgetChat();\n");
      out.write("\t   \n");
      out.write("\t   /*  var items=msg.data.split(\"|\");\n");
      out.write("      var sender = items[0];\n");
      out.write("      var message = items[1];\n");
      out.write("      var date = items[2];\n");
      out.write("      var data ={sender:sender, message:message, date:date};\n");
      out.write("      var temp = Handlebars.compile($(\"#temp\").html());\n");
      out.write("      $(\"#chat\").append(temp(data)); */\n");
      out.write("   }\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
